name: delta_subur_prima
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  http: ^1.2.0
  badges: ^3.1.2
  flutter: 
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_barcode_scanner: ^2.0.0
  socket_io_client: ^2.0.3+1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/logodsp.png
    - assets/images/pattern.png
  fonts:
    - family: Peanut Butter
      fonts:
        - asset: assets/font/peanut_butter_2/Peanut Butter.ttf
    - family: roboto
      fonts:
        - asset: assets/font/roboto/Roboto-Regular.ttf


